"use client";
import { FormEvent, useMemo, useState } from "react";

type Slot = { label: string; iso: string };
const slots: Slot[] = [
  { label: "9:00 AM", iso: "2025-04-16T08:00:00.000Z" }, { label: "9:30 AM", iso: "2025-04-16T08:30:00.000Z" }, { label: "10:30 AM", iso: "2025-04-16T09:30:00.000Z" }, { label: "11:00 AM", iso: "2025-04-16T10:00:00.000Z" }, { label: "2:00 PM", iso: "2025-04-16T13:00:00.000Z" }, { label: "2:30 PM", iso: "2025-04-16T13:30:00.000Z" }, { label: "3:30 PM", iso: "2025-04-16T14:30:00.000Z" }, { label: "4:00 PM", iso: "2025-04-16T15:00:00.000Z" },
];

export function BookingForm({ slug }: { slug: string }) {
  const [selected, setSelected] = useState<Slot | null>(null);
  const [submitted, setSubmitted] = useState(false);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");
  const zone = useMemo(() => Intl.DateTimeFormat().resolvedOptions().timeZone || "Africa/Lagos", []);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!selected) return; setBusy(true); setError(""); const form = new FormData(event.currentTarget); const response = await fetch("/api/bookings", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ slug, eventTypeId: "intro-consultation", startsAt: selected.iso, timeZone: zone, inviteeName: form.get("name"), inviteeEmail: form.get("email"), note: form.get("note") }) }); setBusy(false); if (response.ok) setSubmitted(true); else { const body = await response.json().catch(() => ({})); setError(body.message || "That time was just booked. Please choose another slot."); } }
  if (submitted) return <div className="py-10 text-center"><div className="mx-auto grid h-14 w-14 place-items-center rounded-full bg-emerald-100 text-2xl text-emerald-700">✓</div><h2 className="mt-5 text-2xl font-bold">You’re booked!</h2><p className="mx-auto mt-3 max-w-sm leading-6 text-slate-600">A confirmation with the meeting details is on its way to your inbox.</p><div className="mt-6 rounded-xl bg-slate-50 p-4 text-sm text-slate-700"><p className="font-semibold">Intro consultation</p><p className="mt-1">Wednesday, April 16 · {selected?.label}</p><p className="mt-1 text-slate-500">{zone}</p></div></div>;
  return <form onSubmit={submit}><p className="text-xs font-semibold uppercase tracking-wider text-slate-400">1. Choose a time</p><div className="mt-3 grid grid-cols-2 gap-2">{slots.map(slot => <button key={slot.iso} type="button" onClick={() => setSelected(slot)} className={`rounded-xl border px-3 py-2.5 text-sm font-medium transition ${selected?.iso === slot.iso ? "border-brand-600 bg-brand-50 text-brand-700 ring-1 ring-brand-600" : "border-slate-200 hover:border-brand-300 hover:bg-brand-50"}`}>{slot.label}</button>)}</div><p className="mt-4 text-xs text-slate-500">Times shown in {zone}. <button type="button" className="font-semibold text-brand-600">Change</button></p><div className="my-7 border-t" /><p className="text-xs font-semibold uppercase tracking-wider text-slate-400">2. Your details</p><label className="label mt-4 block">Name<input required name="name" className="field" placeholder="Your name" /></label><label className="label mt-4 block">Email<input required type="email" name="email" className="field" placeholder="you@example.com" /></label><label className="label mt-4 block">Anything Alex should know? <span className="font-normal text-slate-400">(optional)</span><textarea name="note" className="field min-h-24 resize-y" placeholder="Add a note..." /></label>{error && <p role="alert" className="mt-4 rounded-lg bg-rose-50 p-3 text-sm text-rose-700">{error}</p>}<button disabled={!selected || busy} className="button-primary mt-6 w-full">{busy ? "Confirming…" : selected ? "Confirm booking" : "Choose a time to continue"}</button><p className="mt-4 text-center text-xs leading-5 text-slate-500">By booking, you agree to receive appointment-related emails.</p></form>;
}
